name: Test reverse dependencies
on:
  pull_request:
  workflow_dispatch:
jobs:
  reverse_dependencies:
    name: Reverse dependency testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
            lfs: true

      - uses: martinfleis/reverse-dependency-testing@main
        with:
            package_name: "sunpy"
            install: "sunpy,setuptools-scm,extension-helpers,pytest-arraydiff,pytest-doctestplus" # use this to install dependencies - need to support yml
            installation_command: pip install --no-deps --no-build-isolation .
            exclude: "fisspy"